# Site settings
title: Arquebuz.com
description: A collection of travel notes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.areqbuz.com" # the base hostname & protocol for your site
twitter_username: twitterusername
github_username:  githubusername

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title/

google_analytics: UA-80651813-1add 